# Code Generated by ZenTest v. 3.10.0
#                 classname: asrt / meth =  ratio%
#            ChordConverter:    0 /    4 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST
require 'lib/chord'

class TestChordConverter < Test::Unit::TestCase

  def setup
    @input = "[Am7]Do what I say, or I will suffer"
    @result = "[Am7]\nDo what I say, or I will suffer\n"
  end

  def test_process
    raise NotImplementedError, 'Need to write test_process'
  end

  def test_process_line
    chord = ChordConverter.new
    assert_equal(@result, chord.process_line(@input))
  end

  def test_process_token
    raise NotImplementedError, 'Need to write test_process_token'
  end
end

# Number of errors detected: 4
